version: '3.8'

services:
  coco_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - coco_postgres
      - coco_qdrant
      - coco_neo4j
    environment:
      - COCOINDEX_DATABASE_URL=postgresql://postgres:postgres@coco_postgres:5432/cocoindex
      - QDRANT_URL=http://coco_qdrant:6334
      - NEO4J_URI=bolt://coco_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
    volumes:
      - ./data_to_index:/data_to_index  # Host folder to be indexed
    ports:
      - "8000:8000"  # MCP server port

  coco_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocoindex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  coco_qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  coco_neo4j:
    image: neo4j:5
    restart: always
    environment:
      NEO4J_AUTH: neo4j/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  pgdata:
  qdrant_storage:
  neo4j_data: 